version: "3.9"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: unless-stopped
    networks: [fleetnet]

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on: [prometheus]
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks: [fleetnet]

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    pid: host
    network_mode: host
    restart: unless-stopped

  # Postgres Exporter (adjust DSN to your DB)
  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:1234@postgres:5432/fleet_db?sslmode=disable"
    ports:
      - "9187:9187"
    restart: unless-stopped
    networks: [fleetnet]

  # OPTIONAL: Kafka lag exporter (if you want consumer lag dashboards)
  # Assumes your Kafka runs from docker-compose.kafka.yml
  kafka_exporter:
    image: danielqsj/kafka-exporter:latest
    container_name: kafka_exporter
    command:
      - "--kafka.server=host.docker.internal:9092"
    ports:
      - "9308:9308"
    restart: unless-stopped
    networks: [fleetnet]

networks:
  fleetnet:
    external: false
