version: "2" # Docker Compose file format version

services:
  # -----------------------------
  # ZOOKEEPER SERVICE
  # -----------------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4 # Confluent's Zookeeper image (version matches Kafka version)
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181 # Port on which Zookeeper listens for client connections
      ZOOKEEPER_TICK_TIME: 2000 # Heartbeat interval between Zookeeper servers (in ms)
    ports:
      - "2181:2181" # Map container's port 2181 to host's port 2181 (access from local machine)

  # -----------------------------
  # KAFKA SERVICE
  # -----------------------------
  kafka:
    image: confluentinc/cp-kafka:7.4.4 # Confluent's Kafka image (same major/minor version as Zookeeper)
    depends_on:
      - zookeeper # Ensure Zookeeper starts before Kafka
    ports:
      - "9092:9092" # Map Kafka broker port to host so local apps can connect
    environment:
      KAFKA_BROKER_ID: 1 # Unique ID for the Kafka broker (needed for clusters)
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 # Tell Kafka where to find Zookeeper (service name:port)
      KAFKA_ADVERTISED_LISTENERS:
        PLAINTEXT://localhost:9092
        # How Kafka tells clients to connect to it — here it's accessible via localhost:9092 from the host machine
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:
        1
        # Replication factor for internal Kafka topics (1 means no redundancy — fine for local dev)
# Rumning the services:
# Start Kafka and Zookeeper in background mode:  docker-compose -f docker-compose.kafka.yml up -d

# Check if both services are running: docker-compose -f docker-compose.kafka.yml ps, you should see zookeeper Up ... and kafka Up ...

# Find Kafka container name dynamically & create a topic called 'fleet-data', Run this command:
# docker exec -it $(docker ps -qf "name=kafka") kafka-topics \
#  --create \
#  --topic fleet-data \
#  --bootstrap-server localhost:9092 \
#  --partitions 1 \
#  --replication-factor 1

# Verify topic creation

# docker exec -it $(docker ps -qf "name=kafka") kafka-topics \
#  --list \
#  --bootstrap-server localhost:9092

# Stop the services: docker-compose -f docker-compose.kafka.yml down
