{
 "title": "Traffic Density Over Time",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Driving Safety Events Over Time",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "fleet_db",
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  COUNT(*) FILTER (WHERE braking_event) AS braking_events,\n  COUNT(*) FILTER (WHERE collision_alert) AS collision_alerts\nFROM fleet_stream_processed\nWHERE $__timeFilter(timestamp)\nGROUP BY 1\nORDER BY timestamp DESC\n"
    }
   ]
  },
  {
   "title": "Road Type Frequency Over Time.",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "fleet_db",
     "rawSql": "SELECT\n  date_trunc('day', timestamp) AS \"time\",\n  road_type,\n  COUNT(*) AS count\nFROM fleet_stream_processed\nWHERE $__timeFilter(timestamp)\nGROUP BY 1, 2\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Traffic Density Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "fleet_db",
     "rawSql": "SELECT\n  DATE_TRUNC('hour', timestamp) AS time,\n  traffic_density,\n  COUNT(*) AS count\nFROM fleet_stream_processed\nWHERE $__timeFilter(timestamp)\nGROUP BY 1, 2\nORDER BY 1\n"
    }
   ]
  }
 ]
}