global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus self
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # Host-level metrics
  - job_name: "node_exporter"
    static_configs:
      - targets: ["host.docker.internal:9100"] # or 'node_exporter:9100' if not host network

  # PostgreSQL metrics
  - job_name: "postgres_exporter"
    static_configs:
      - targets: ["postgres_exporter:9187"]

  # Kafka consumer lag (optional)
  - job_name: "kafka_exporter"
    static_configs:
      - targets: ["kafka_exporter:9308"]

  # Batch ETL Python job (we'll expose 8001)
  - job_name: "batch_etl"
    static_configs:
      - targets: ["host.docker.internal:8001"]

  # Streaming ETL Python job (we'll expose 8002)
  - job_name: "streaming_etl"
    static_configs:
      - targets: ["host.docker.internal:8002"]
