FROM apache/airflow:2.9.0

# Install Java + Spark dependencies
USER root
RUN apt-get update && apt-get install -y \
    default-jdk \
    wget \
    tar \
    unzip \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Set JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV PATH="$JAVA_HOME/bin:$PATH:/opt/spark/bin"

# Install Python dependencies
COPY requirements.txt /requirements.txt
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r /requirements.txt

# Copy project code
COPY etl /opt/airflow/etl
COPY dags /opt/airflow/dags
COPY config /opt/airflow/config
COPY lib /opt/airflow/lib

# Install Spark
RUN mkdir -p /opt/spark && \
    wget https://dlcdn.apache.org/spark/spark-3.5.6/spark-3.5.6-bin-hadoop3.tgz -O /tmp/spark.tgz && \
    tar -xzf /tmp/spark.tgz --strip-components=1 -C /opt/spark && \
    rm /tmp/spark.tgz

USER airflow
